# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Shutdown Default Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
        
      - name: Install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'my_db'
          mysql user: root
          mysql password: root
          
      - name: Start MySQL
        run: sudo service mysql start
        
      - name: Verify MySQL
        run: mysql --user=root --password=root
        
      - name: Create table nutrecipe
        run: |
          mysql --user=root --password=root --execute "CREATE DATABASE NUTRECIPE;"
          mysql -e "USE nutrecipe;"
          mysql -e "SELECT database ();"
          mysql --user=root --password=root --execute "CREATE TABLE ingredients;"
        
      - name: List existing SQL databases
        run: mysql --user=root --password=root --execute="show databases;"
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: npm ci
      - run: npm run build --if-present

      - name: Cypress run (Chrome)
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run start:dev
          wait-on: "http://127.0.0.1:3000"
