# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    env:
      DB_DATABASE: nutrecipe
      DB_USER: root
      DB_PASSWORD: root
    steps:
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: List existing SQL databases
      run: mysql --user=root --password=root --execute="show databases;"

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    #- name: Cypress run (Chrome)
      #uses: cypress-io/github-action@v2
      #with:
        #browser: chrome
        #headless: true
        #start: npm run start:dev
        #wait-on: "http://127.0.0.1:3000"
      #env:
        #CYPRESS_host: "http://localhost"
        #CYPRESS_port: 4020
