# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Shutdown Default Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
        
      - name: Install MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: '8.0'
          mysql database: 'my_db'
          mysql user: root
          mysql password: root
          
      - name: Start MySQL
        run: sudo service mysql start
        
      - name: Verify MySQL
        run: mysql --user=root --password=root
        
      - name: Create NUTRECIPE Database
        run: mysql --user=root --password=root --execute="CREATE DATABASE IF NOT EXISTS NUTRECIPE;"
        
      - name: Create ingredients table
        run: mysql --user=root --password=root -D NUTRECIPE --execute="CREATE TABLE IF NOT EXISTS INGREDIENTS ( ingredientId int );"
        
      - name: Create recipes table
        run: mysql --user=root --password=root -D NUTRECIPE --execute="CREATE TABLE IF NOT EXISTS RECIPES ( recipeId int );"
        
      - name: Create users table
        run: mysql --user=root --password=root -D NUTRECIPE --execute="CREATE TABLE IF NOT EXISTS USERS ( userId int );"
        
      - name: Create bookmarkingredients table
        run: mysql --user=root --password=root -D NUTRECIPE --execute="CREATE TABLE IF NOT EXISTS BOOKMARKINGREDIENTS (   `id` int NOT NULL AUTO_INCREMENT,`ingredientId` int NOT NULL,`userId` int NOT NULL,`saved` tinyint(1) NOT NULL,`createdAt` datetime NOT NULL,`updatedAt` datetime NOT NULL,PRIMARY KEY (`id`),KEY `ingredientId` (`ingredientId`),KEY `userId` (`userId`)) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;"
        
      - name: Create bookmarkrecipes table
        run: mysql --user=root --password=root -D NUTRECIPE --execute="CREATE TABLE IF NOT EXISTS BOOKMARKRECIPES ( ingId int );"
        
      - name: Show tables in NUTRECIPE Database
        run: mysql --user=root --password=root -D NUTRECIPE --execute="show tables;"
        
      - name: List existing SQL databases
        run: mysql --user=root --password=root --execute="show databases;"

